[phases.setup]
nixPkgs = ['dotnet-sdk_9']

[phases.build]
cmds = [
    'dotnet restore GuardiaoDasMemorias.sln',
    'dotnet publish GuardiaoDasMemorias/GuardiaoDasMemorias.csproj -c Release -o out'
]

[start]
cmd = 'cd out && dotnet GuardiaoDasMemorias.dll'
